#number of similar text chunks to select for context
top_k: 3

#name of the llm model
model_name: "mistralai/Mistral-7B-Instruct-v0.1"

#model parameters
model_params: 
  max_new_tokens: 512 
  top_p: 0.5
  temperature: 0.2
  repetition_penalty: 1.2

#embedding model name
#sentence-transformers/all-mpnet-base-v2
embedding_model_name: "sentence-transformers/all-MiniLM-L6-v2"

# the url of the dataset
data_url: 'otalorajuand/data_house_museum'